# Generated by Django 3.2.7 on 2021-09-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Трата',
                'verbose_name_plural': 'Траты',
            },
        ),
        migrations.CreateModel(
            name='SpendingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=256)),
                ('subtype', models.TextField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Тип траты',
                'verbose_name_plural': 'Типы трат',
            },
        ),
        migrations.AddConstraint(
            model_name='spendingtype',
            constraint=models.UniqueConstraint(fields=('type', 'subtype'), name='type-subtype constraint'),
        ),
        migrations.AddField(
            model_name='spending',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spending.spendingtype'),
        ),
    ]
